# Generated by Django 4.0.6 on 2022-07-12 17:52

import authentication.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=authentication.models.upload_to_id_image),
        ),
    ]
