# Generated by Django 4.0.6 on 2022-07-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='feature_image',
            field=models.ImageField(upload_to='hotels/%Y/%m/%d/'),
        ),
    ]
