# Generated by Django 4.0.6 on 2022-07-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_hotel_feature_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
