# Generated by Django 4.0.6 on 2022-07-11 20:38

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_hotel_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='specifications',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='feature_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='hotels/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
