# Generated by Django 4.0.6 on 2022-07-12 17:53

from django.db import migrations, models
import django.db.models.deletion
import hotel.models.HotelImage
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_alter_hotel_feature_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=hotel.models.HotelImage.upload_to_id_image)),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
            ],
        ),
    ]
