# Generated by Django 4.0.6 on 2022-07-12 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_hotelimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelimage',
            old_name='hotel_id',
            new_name='hotel',
        ),
    ]
