# Generated by Django 4.0.6 on 2022-07-25 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelreview',
            name='rating',
        ),
        migrations.AddField(
            model_name='hotelreview',
            name='cleanliness',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='hotelreview',
            name='location',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='hotelreview',
            name='services',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='hotelreview',
            name='value_of_money',
            field=models.FloatField(default=0.0),
        ),
    ]
